name: CI
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@master
      - name: Yarn Install
        # already run build here
        run: yarn
      - name: Check Format
        run: yarn format:check
