name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@master
      - name: Yarn Install
        run: yarn
      - name: Check Format
        run: yarn format:check
      - name: Build
        run: yarn workspaces run build
